languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "app/SymfonyRequirements.php"
- "app/check.php"
- "composer.lock"
- ".git/"
- ".git/"
- "app/cache/"
- "app/logs/"
- "node_modules/"
- "app/Resources/bower_components/"
