sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose -f docker-compose-test.yml up -d

script:
  - docker-compose -f docker-compose-test.yml run site composer checkerror
  - docker-compose -f docker-compose-test.yml run site composer checkstyle
  - docker-compose -f docker-compose-test.yml run site composer test
