sudo: required

services:
  - docker

install:
  - docker build -t romainprignon/starter-symfony-front .
  - docker run -p 80:80 -e "env=test" -e "SYMFONY_ENV=test" romainprignon/starter-symfony-front

script:
  - composer run-script checkerror
  - composer run-script checkstyle
  - composer run-script test
