language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - PATH=$PATH:./bin

cache:
  directories:
    - vendor/
    - node_modules/
    - app/Resources/bower_components/

matrix:
  fast_finish: true

addons:
  code_climate:
    repo_token: tobedefined

before_install:
  - composer self-update
  - npm install -g npm

install:
  - composer install
  - npm install
  - npm run bower install

before_script:
  - npm run task build

script:
  - composer checkerror
  - composer checkstyle
  - composer test

after_script:
  - CODECLIMATE_REPO_TOKEN="tobedefined" bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
