site-from_src:
  build: .
  environment:
    - env=prod
  restart: always

site-from_dist:
  image: "romainprignon/starter-symfony-front"
  ports:
    - "80:80"
  environment:
    - env=prod
  restart: always
